### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by robweber** [dcmeglio/waste_management#1]
Hi, 

I am using your HA Waste Management integration - thank you for building and providing it. It's been very useful. Just a question on if/how the API you're using in this library is different than the one Waste Management has documented at [https://api.wm.com/](https://api.wm.com/)? 

I can't seem to find any of the endpoints you are using, and the URLs are different (https://api.wm.com vs https://rest-api.wm.com). The one WM has documented has some additional endpoints for ETA that could be useful for HA integration. Curious if they are indeed different or if some additional pieces could be added using these other endpoints?

**Comment by dcmeglio** [comment]
It's not. I used the API the website uses. While I'd like to use the one you linked there, though I requested an API key several times, I never heard back.

**Comment by robweber** [comment]
Thanks! That makes sense - I kind of wondered if that was the URL for the internal API their own customer site would use. Great job on the reverse engineering.
